import axios from "axios"
import { getHeaders } from "../auth/authService"
const BASE = "http://localhost:8000"
export const login = (d) => axios.post(`${BASE}/login`, d)
export const changePassword = (d) => axios.post(`${BASE}/changePassword`, d)
export const getProfile = () => axios.get(`${BASE}/user/profile`, { headers: getHeaders() })
export const updateProfile = (d) => axios.post(`${BASE}/user/updateProfile`, d, { headers: getHeaders() })
export const getDashboardStats = () => axios.get(`${BASE}/admin/dashboardStats`, { headers: getHeaders() })
export const getAdminUsers = () => axios.get(`${BASE}/admin/users`, { headers: getHeaders() })
export const updateUserStatus = (d) => axios.post(`${BASE}/admin/updateUserStatus`, d, { headers: getHeaders() })
export const getAdminCategories = () => axios.get(`${BASE}/admin/categories`, { headers: getHeaders() })
export const addCategory = (d) => axios.post(`${BASE}/admin/addCategory`, d, { headers: getHeaders() })
export const updateCategory = (d) => axios.post(`${BASE}/admin/updateCategory`, d, { headers: getHeaders() })
export const deleteCategory = (id) => axios.get(`${BASE}/admin/deleteCategory/${id}`, { headers: getHeaders() })
export const getAdminItems = () => axios.get(`${BASE}/admin/items`, { headers: getHeaders() })
export const addItem = (d) => axios.post(`${BASE}/admin/addItem`, d, { headers: getHeaders() })
export const updateItem = (d) => axios.post(`${BASE}/admin/updateItem`, d, { headers: getHeaders() })
export const deleteItem = (id) => axios.get(`${BASE}/admin/deleteItem/${id}`, { headers: getHeaders() })
export const getInventory = () => axios.get(`${BASE}/admin/inventory`, { headers: getHeaders() })
export const addInventory = (d) => axios.post(`${BASE}/admin/addInventory`, d, { headers: getHeaders() })
export const updateInventory = (d) => axios.post(`${BASE}/admin/updateInventory`, d, { headers: getHeaders() })
export const deleteInventory = (id) => axios.get(`${BASE}/admin/deleteInventory/${id}`, { headers: getHeaders() })
export const getAdminOrders = () => axios.get(`${BASE}/admin/orders`, { headers: getHeaders() })
export const updateOrderStatus = (d) => axios.post(`${BASE}/admin/updateOrderStatus`, d, { headers: getHeaders() })
export const getAdminPayments = () => axios.get(`${BASE}/admin/payments`, { headers: getHeaders() })
export const getAdminFeedbacks = () => axios.get(`${BASE}/admin/feedbacks`, { headers: getHeaders() })
